[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/wb/*"
  to   = "https://a.windbornesystems.com/treasure/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[headers]]
  for = "/wb/*"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
  Pragma = "no-cache"