[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/wb/*"
  to   = "https://a.windbornesystems.com/treasure/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
